-- HomeGlow PostgreSQL baseline schema (equivalent to SQLite schema version 14).
-- Loaded once on a fresh PostgreSQL database instead of replaying the SQLite
-- migration chain (see docs/db-abstraction-and-postgres-plan.md, section 7).
--
-- Conventions chosen to mirror the SQLite runtime so the same app code works
-- unchanged: integer 0/1 flags stay INTEGER; timestamps are stored as text in
-- 'YYYY-MM-DD HH24:MI:SS' (UTC) form; JSON is stored as text. Identity columns use
-- GENERATED BY DEFAULT so explicit ids (data migration, the seeded bonus user)
-- and auto-generated ids both work.

CREATE TABLE IF NOT EXISTS chores (
    id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title         TEXT NOT NULL,
    description   TEXT,
    clam_value    INTEGER DEFAULT 0
);

CREATE TABLE IF NOT EXISTS users (
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username        TEXT,
    email           TEXT,
    profile_picture TEXT
);

CREATE TABLE IF NOT EXISTS events (
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     INTEGER,
    summary     TEXT,
    start       TEXT,
    "end"       TEXT,
    description TEXT
);

CREATE TABLE IF NOT EXISTS settings (
    key   TEXT PRIMARY KEY,
    value TEXT
);

CREATE TABLE IF NOT EXISTS prizes (
    id        INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name      TEXT NOT NULL,
    clam_cost INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS calendar_sources (
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       TEXT NOT NULL,
    type       TEXT NOT NULL,
    url        TEXT NOT NULL,
    username   TEXT,
    password   TEXT,
    color      TEXT NOT NULL DEFAULT '#6e44ff',
    enabled    INTEGER NOT NULL DEFAULT 1,
    sort_order INTEGER NOT NULL DEFAULT 0,
    created_at TEXT DEFAULT to_char((now() AT TIME ZONE 'UTC'), 'YYYY-MM-DD HH24:MI:SS')
);
CREATE INDEX IF NOT EXISTS idx_calendar_sources_enabled ON calendar_sources(enabled);
CREATE INDEX IF NOT EXISTS idx_calendar_sources_sort_order ON calendar_sources(sort_order);

CREATE TABLE IF NOT EXISTS photo_sources (
    id                    INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name                  TEXT NOT NULL,
    type                  TEXT NOT NULL,
    url                   TEXT,
    api_key               TEXT,
    username              TEXT,
    password              TEXT,
    album_id              TEXT,
    refresh_token         TEXT,
    enabled               INTEGER NOT NULL DEFAULT 1,
    sort_order            INTEGER NOT NULL DEFAULT 0,
    created_at            TEXT DEFAULT to_char((now() AT TIME ZONE 'UTC'), 'YYYY-MM-DD HH24:MI:SS'),
    picker_session_id     TEXT,
    picker_session_expire TEXT
);
CREATE INDEX IF NOT EXISTS idx_photo_sources_enabled ON photo_sources(enabled);
CREATE INDEX IF NOT EXISTS idx_photo_sources_sort_order ON photo_sources(sort_order);

CREATE TABLE IF NOT EXISTS admin_pin (
    id         INTEGER PRIMARY KEY CHECK (id = 1),
    pin_hash   TEXT NOT NULL,
    created_at TEXT DEFAULT to_char((now() AT TIME ZONE 'UTC'), 'YYYY-MM-DD HH24:MI:SS'),
    updated_at TEXT DEFAULT to_char((now() AT TIME ZONE 'UTC'), 'YYYY-MM-DD HH24:MI:SS')
);

CREATE TABLE IF NOT EXISTS devices (
    id                   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name                 TEXT NOT NULL UNIQUE,
    updateTime           TEXT DEFAULT to_char((now() AT TIME ZONE 'UTC'), 'YYYY-MM-DD HH24:MI:SS'),
    device_settings_json TEXT
);
CREATE INDEX IF NOT EXISTS idx_devices_device_name ON devices(name);

CREATE TABLE IF NOT EXISTS tabs (
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    device_name TEXT NOT NULL,
    number      INTEGER NOT NULL,
    label       TEXT NOT NULL,
    icon        TEXT NOT NULL,
    show_label  INTEGER DEFAULT 1,
    created_at  TEXT DEFAULT to_char((now() AT TIME ZONE 'UTC'), 'YYYY-MM-DD HH24:MI:SS'),
    config_json TEXT,
    FOREIGN KEY (device_name) REFERENCES devices(name) ON DELETE CASCADE ON UPDATE CASCADE,
    UNIQUE (device_name, number)
);
CREATE INDEX IF NOT EXISTS idx_tabs_device_name ON tabs(device_name);

CREATE TABLE IF NOT EXISTS chore_schedules (
    id                 INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    chore_id           INTEGER NOT NULL,
    user_id            INTEGER,
    crontab            TEXT,
    visible            INTEGER NOT NULL DEFAULT 1,
    created_at         TEXT DEFAULT to_char((now() AT TIME ZONE 'UTC'), 'YYYY-MM-DD HH24:MI:SS'),
    duration           TEXT DEFAULT 'day-of',
    interval           TEXT,
    parent_schedule_id INTEGER REFERENCES chore_schedules(id) ON DELETE SET NULL,
    FOREIGN KEY (chore_id) REFERENCES chores(id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_chore_schedules_chore_id ON chore_schedules(chore_id);
CREATE INDEX IF NOT EXISTS idx_chore_schedules_user_id ON chore_schedules(user_id);
CREATE INDEX IF NOT EXISTS idx_chore_schedules_visible ON chore_schedules(visible);
CREATE INDEX IF NOT EXISTS idx_chore_schedules_duration ON chore_schedules(duration);
CREATE INDEX IF NOT EXISTS idx_chore_schedules_parent_schedule_id ON chore_schedules(parent_schedule_id);

CREATE TABLE IF NOT EXISTS chore_history (
    id                INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id           INTEGER NOT NULL,
    chore_schedule_id INTEGER REFERENCES chore_schedules(id) ON DELETE SET NULL,
    date              TEXT NOT NULL,
    clam_value        INTEGER NOT NULL DEFAULT 0,
    created_at        TEXT DEFAULT to_char((now() AT TIME ZONE 'UTC'), 'YYYY-MM-DD HH24:MI:SS'),
    title             TEXT
);
CREATE INDEX IF NOT EXISTS idx_chore_history_user_id ON chore_history(user_id);
CREATE INDEX IF NOT EXISTS idx_chore_history_date ON chore_history(date);
CREATE INDEX IF NOT EXISTS idx_chore_history_user_date ON chore_history(user_id, date);
-- FK index that was missing in the SQLite schema (see FK audit in the plan).
CREATE INDEX IF NOT EXISTS idx_chore_history_chore_schedule_id ON chore_history(chore_schedule_id);

CREATE TABLE IF NOT EXISTS calendar_events_cache (
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_id   INTEGER NOT NULL,
    event_uid   TEXT NOT NULL,
    title       TEXT,
    start_time  TEXT NOT NULL,
    end_time    TEXT NOT NULL,
    description TEXT,
    location    TEXT,
    all_day     INTEGER DEFAULT 0,
    raw_data    TEXT,
    created_at  TEXT DEFAULT to_char((now() AT TIME ZONE 'UTC'), 'YYYY-MM-DD HH24:MI:SS'),
    FOREIGN KEY (source_id) REFERENCES calendar_sources(id) ON DELETE CASCADE,
    UNIQUE (source_id, event_uid, start_time)
);
CREATE INDEX IF NOT EXISTS idx_cache_source_id ON calendar_events_cache(source_id);
CREATE INDEX IF NOT EXISTS idx_cache_start_time ON calendar_events_cache(start_time);
CREATE INDEX IF NOT EXISTS idx_cache_end_time ON calendar_events_cache(end_time);

CREATE TABLE IF NOT EXISTS calendar_sync_status (
    source_id             INTEGER PRIMARY KEY,
    last_sync_at          TEXT,
    last_sync_status      TEXT,
    last_sync_message     TEXT,
    event_count           INTEGER DEFAULT 0,
    sync_interval_minutes INTEGER DEFAULT 15,
    FOREIGN KEY (source_id) REFERENCES calendar_sources(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS google_accounts (
    id                INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    google_sub        TEXT UNIQUE,
    email             TEXT,
    name              TEXT,
    picture           TEXT,
    access_token_enc  TEXT,
    refresh_token_enc TEXT,
    token_expiry      TEXT,
    scopes            TEXT,
    created_at        TEXT DEFAULT to_char((now() AT TIME ZONE 'UTC'), 'YYYY-MM-DD HH24:MI:SS'),
    updated_at        TEXT DEFAULT to_char((now() AT TIME ZONE 'UTC'), 'YYYY-MM-DD HH24:MI:SS')
);

CREATE TABLE IF NOT EXISTS google_oauth_states (
    state        TEXT PRIMARY KEY,
    redirect_uri TEXT NOT NULL,
    return_url   TEXT,
    created_at   TEXT DEFAULT to_char((now() AT TIME ZONE 'UTC'), 'YYYY-MM-DD HH24:MI:SS')
);
CREATE INDEX IF NOT EXISTS idx_google_oauth_states_created ON google_oauth_states(created_at);

CREATE TABLE IF NOT EXISTS google_picked_media (
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_id       INTEGER NOT NULL,
    google_media_id TEXT NOT NULL,
    filename        TEXT,
    mime_type       TEXT,
    local_path      TEXT NOT NULL,
    width           INTEGER,
    height          INTEGER,
    created_time    TEXT,
    downloaded_at   TEXT DEFAULT to_char((now() AT TIME ZONE 'UTC'), 'YYYY-MM-DD HH24:MI:SS'),
    UNIQUE (source_id, google_media_id),
    FOREIGN KEY (source_id) REFERENCES photo_sources(id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_google_picked_media_source ON google_picked_media(source_id);

CREATE TABLE IF NOT EXISTS homeglow_photos (
    id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_id     INTEGER NOT NULL,
    filename      TEXT NOT NULL,
    original_name TEXT,
    mime_type     TEXT,
    size          INTEGER,
    uploaded_at   TEXT DEFAULT to_char((now() AT TIME ZONE 'UTC'), 'YYYY-MM-DD HH24:MI:SS'),
    FOREIGN KEY (source_id) REFERENCES photo_sources(id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_homeglow_photos_source ON homeglow_photos(source_id);

-- Seed the bonus user (id = 0) and stamp the schema version.
INSERT INTO users (id, username, email, profile_picture)
VALUES (0, 'bonus', 'bonus@example.com', '')
ON CONFLICT (id) DO NOTHING;

INSERT INTO settings (key, value)
VALUES ('SYSTEM_SCHEMA_ID', '14')
ON CONFLICT (key) DO NOTHING;
